In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

# Web Scraper

## First Step: Walk before you run

Let's scrape some data!

But first thing first, we need to import necessary libraries.

In [2]:
from bs4 import BeautifulSoup
import requests

If your input is a URL string, Beautiful Soup’s `.get()` method will not fetch or download the web page for you. Beautiful Soup is purely a parsing library; it cannot make network requests.

To download a web page using a URL, you must first use a HTTP library like `requests`, and then pass that downloaded content into Beautiful Soup.

In [3]:
url = "https://quotes.toscrape.com/"

response = requests.get(url)

The primary purpose of the `requests` library in Python is to send HTTP requests to web servers so you can download web pages, interact with APIs, and transfer data.

It acts as a web browser without a graphical interface, allowing Python scripts to communicate directly with the internet.

And... there you go, you got some raw materials for further processing!

In [4]:
type(response)

requests.models.Response

- `response.headers`: Returns a case-insensitive dictionary containing the response headers.
- `response.url`: Returns the final URL string of the response as a string.
- `response.text`: Returns the response body as a string.
- And more...

In [5]:
response.headers

{'Date': 'Thu, 27 Aug 2026 03:27:23 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '11064', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=0; includeSubDomains; preload'}

In [6]:
response.url

'https://quotes.toscrape.com/'

In [7]:
response.text

'<!DOCTYPE html>\n<html lang="en">\n<head>\n\t<meta charset="UTF-8">\n\t<title>Quotes to Scrape</title>\n    <link rel="stylesheet" href="/static/bootstrap.min.css">\n    <link rel="stylesheet" href="/static/main.css">\n    \n    \n</head>\n<body>\n    <div class="container">\n        <div class="row header-box">\n            <div class="col-md-8">\n                <h1>\n                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>\n                </h1>\n            </div>\n            <div class="col-md-4">\n                <p>\n                \n                    <a href="/login">Login</a>\n                \n                </p>\n            </div>\n        </div>\n    \n\n<div class="row">\n    <div class="col-md-8">\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>\n        <span>by <small class="author" itemprop="author">Albert Einstein</small>\n        <a href="/author/Albert-Einstein">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world" /    > \n            \n            <a class="tag" href="/tag/change/page/1/">change</a>\n            \n            <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>\n            \n            <a class="tag" href="/tag/thinking/page/1/">thinking</a>\n            \n            <a class="tag" href="/tag/world/page/1/">world</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>\n        <span>by <small class="author" itemprop="author">J.K. Rowling</small>\n        <a href="/author/J-K-Rowling">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="abilities,choices" /    > \n            \n            <a class="tag" href="/tag/abilities/page/1/">abilities</a>\n            \n            <a class="tag" href="/tag/choices/page/1/">choices</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>\n        <span>by <small class="author" itemprop="author">Albert Einstein</small>\n        <a href="/author/Albert-Einstein">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="inspirational,life,live,miracle,miracles" /    > \n            \n            <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>\n            \n            <a class="tag" href="/tag/life/page/1/">life</a>\n            \n            <a class="tag" href="/tag/live/page/1/">live</a>\n            \n            <a class="tag" href="/tag/miracle/page/1/">miracle</a>\n            \n            <a class="tag" href="/tag/miracles/page/1/">miracles</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>\n        <span>by <small class="author" itemprop="author">Jane Austen</small>\n        <a href="/author/Jane-Austen">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="aliteracy,books,classic,humor" /    > \n            \n            <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>\n            \n            <a class="tag" href="/tag/books/page/1/">books</a>\n            \n            <a class="tag" href="/tag/classic/page/1/">classic</a>\n            \n            <a class="tag" href="/tag/humor/page/1/">humor</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it&#39;s better to be absolutely ridiculous than absolutely boring.”</span>\n        <span>by <small class="author" itemprop="author">Marilyn Monroe</small>\n        <a href="/author/Marilyn-Monroe">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="be-yourself,inspirational" /    > \n            \n            <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>\n            \n            <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>\n        <span>by <small class="author" itemprop="author">Albert Einstein</small>\n        <a href="/author/Albert-Einstein">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="adulthood,success,value" /    > \n            \n            <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>\n            \n            <a class="tag" href="/tag/success/page/1/">success</a>\n            \n            <a class="tag" href="/tag/value/page/1/">value</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>\n        <span>by <small class="author" itemprop="author">André Gide</small>\n        <a href="/author/Andre-Gide">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="life,love" /    > \n            \n            <a class="tag" href="/tag/life/page/1/">life</a>\n            \n            <a class="tag" href="/tag/love/page/1/">love</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“I have not failed. I&#39;ve just found 10,000 ways that won&#39;t work.”</span>\n        <span>by <small class="author" itemprop="author">Thomas A. Edison</small>\n        <a href="/author/Thomas-A-Edison">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="edison,failure,inspirational,paraphrased" /    > \n            \n            <a class="tag" href="/tag/edison/page/1/">edison</a>\n            \n            <a class="tag" href="/tag/failure/page/1/">failure</a>\n            \n            <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>\n            \n            <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it&#39;s in hot water.”</span>\n        <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>\n        <a href="/author/Eleanor-Roosevelt">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="misattributed-eleanor-roosevelt" /    > \n            \n            <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>\n            \n        </div>\n    </div>\n\n    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">\n        <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>\n        <span>by <small class="author" itemprop="author">Steve Martin</small>\n        <a href="/author/Steve-Martin">(about)</a>\n        </span>\n        <div class="tags">\n            Tags:\n            <meta class="keywords" itemprop="keywords" content="humor,obvious,simile" /    > \n            \n            <a class="tag" href="/tag/humor/page/1/">humor</a>\n            \n            <a class="tag" href="/tag/obvious/page/1/">obvious</a>\n            \n            <a class="tag" href="/tag/simile/page/1/">simile</a>\n            \n        </div>\n    </div>\n\n    <nav>\n        <ul class="pager">\n            \n            \n            <li class="next">\n                <a href="/page/2/">Next <span aria-hidden="true">&rarr;</span></a>\n            </li>\n            \n        </ul>\n    </nav>\n    </div>\n    <div class="col-md-4 tags-box">\n        \n            <h2>Top Ten tags</h2>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 28px" href="/tag/love/">love</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 26px" href="/tag/inspirational/">inspirational</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 26px" href="/tag/life/">life</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 24px" href="/tag/humor/">humor</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 22px" href="/tag/books/">books</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 14px" href="/tag/reading/">reading</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 10px" href="/tag/friendship/">friendship</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 8px" href="/tag/friends/">friends</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 8px" href="/tag/truth/">truth</a>\n            </span>\n            \n            <span class="tag-item">\n            <a class="tag" style="font-size: 6px" href="/tag/simile/">simile</a>\n            </span>\n            \n        \n    </div>\n</div>\n\n    </div>\n    <footer class="footer">\n        <div class="container">\n            <p class="text-muted">\n                Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>\n            </p>\n            <p class="copyright">\n                Made with <span class=\'zyte\'>❤</span> by <a class=\'zyte\' href="https://www.zyte.com">Zyte</a>\n            </p>\n        </div>\n    </footer>\n</body>\n</html>'

The text is still messy, noisy, and hard to read.

There is where BeautifulSoup will come in handy. It takes the raw HTML text downloaded from the internet and converts it into a *structured, searchable Python object*.

In [8]:
soup = BeautifulSoup(response.text, "html.parser")

- `BeautifulSoup(...)`: Its job is to build a "parse tree" (a structured map) of the web page which allows you to easily search for specific elements like tables, links, or text instead of manually searching through thousands of lines of raw text.
- `response.text`: Raw HTML material
- `html.parser`: This tells BeautifulSoup which background engine to use to read the HTML.

In [9]:
type(soup)

bs4.BeautifulSoup

In [10]:
all_tags = soup.find_all()
all_tags

[<html lang="en">
 <head>
 <meta charset="utf-8"/>
 <title>Quotes to Scrape</title>
 <link href="/static/bootstrap.min.css" rel="stylesheet"/>
 <link href="/static/main.css" rel="stylesheet"/>
 </head>
 <body>
 <div class="container">
 <div class="row header-box">
 <div class="col-md-8">
 <h1>
 <a href="/" style="text-decoration: none">Quotes to Scrape</a>
 </h1>
 </div>
 <div class="col-md-4">
 <p>
 <a href="/login">Login</a>
 </p>
 </div>
 </div>
 <div class="row">
 <div class="col-md-8">
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
 <a class="tag" href="/tag/change/page/1/">change</a>
 <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
 <a class="tag" href="/tag/thinking/page/1/">thinking</a>
 <a class="tag" href="/tag/world/page/1/">world</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
 <span>by <small class="author" itemprop="author">J.K. Rowling</small>
 <a href="/author/J-K-Rowling">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
 <a class="tag" href="/tag/abilities/page/1/">abilities</a>
 <a class="tag" href="/tag/choices/page/1/">choices</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/live/page/1/">live</a>
 <a class="tag" href="/tag/miracle/page/1/">miracle</a>
 <a class="tag" href="/tag/miracles/page/1/">miracles</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
 <span>by <small class="author" itemprop="author">Jane Austen</small>
 <a href="/author/Jane-Austen">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
 <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
 <a class="tag" href="/tag/books/page/1/">books</a>
 <a class="tag" href="/tag/classic/page/1/">classic</a>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
 <span>by <small class="author" itemprop="author">Marilyn Monroe</small>
 <a href="/author/Marilyn-Monroe">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
 <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
 <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
 <a class="tag" href="/tag/success/page/1/">success</a>
 <a class="tag" href="/tag/value/page/1/">value</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
 <span>by <small class="author" itemprop="author">André Gide</small>
 <a href="/author/Andre-Gide">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="life,love" itemprop="keywords"/>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/love/page/1/">love</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
 <span>by <small class="author" itemprop="author">Thomas A. Edison</small>
 <a href="/author/Thomas-A-Edison">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
 <a class="tag" href="/tag/edison/page/1/">edison</a>
 <a class="tag" href="/tag/failure/page/1/">failure</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
 <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
 <a href="/author/Eleanor-Roosevelt">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
 <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
 <span>by <small class="author" itemprop="author">Steve Martin</small>
 <a href="/author/Steve-Martin">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 <a class="tag" href="/tag/obvious/page/1/">obvious</a>
 <a class="tag" href="/tag/simile/page/1/">simile</a>
 </div>
 </div>
 <nav>
 <ul class="pager">
 <li class="next">
 <a href="/page/2/">Next <span aria-hidden="true">→</span></a>
 </li>
 </ul>
 </nav>
 </div>
 <div class="col-md-4 tags-box">
 <h2>Top Ten tags</h2>
 <span class="tag-item">
 <a class="tag" href="/tag/love/" style="font-size: 28px">love</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/inspirational/" style="font-size: 26px">inspirational</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/life/" style="font-size: 26px">life</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/humor/" style="font-size: 24px">humor</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/books/" style="font-size: 22px">books</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/reading/" style="font-size: 14px">reading</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/friendship/" style="font-size: 10px">friendship</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/friends/" style="font-size: 8px">friends</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/truth/" style="font-size: 8px">truth</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/simile/" style="font-size: 6px">simile</a>
 </span>
 </div>
 </div>
 </div>
 <footer class="footer">
 <div class="container">
 <p class="text-muted">
                 Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
 </p>
 <p class="copyright">
                 Made with <span class="zyte">❤</span> by <a class="zyte" href="https://www.zyte.com">Zyte</a>
 </p>
 </div>
 </footer>
 </body>
 </html>,
 <head>
 <meta charset="utf-8"/>
 <title>Quotes to Scrape</title>
 <link href="/static/bootstrap.min.css" rel="stylesheet"/>
 <link href="/static/main.css" rel="stylesheet"/>
 </head>,
 <meta charset="utf-8"/>,
 <title>Quotes to Scrape</title>,
 <link href="/static/bootstrap.min.css" rel="stylesheet"/>,
 <link href="/static/main.css" rel="stylesheet"/>,
 <body>
 <div class="container">
 <div class="row header-box">
 <div class="col-md-8">
 <h1>
 <a href="/" style="text-decoration: none">Quotes to Scrape</a>
 </h1>
 </div>
 <div class="col-md-4">
 <p>
 <a href="/login">Login</a>
 </p>
 </div>
 </div>
 <div class="row">
 <div class="col-md-8">
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
 <a class="tag" href="/tag/change/page/1/">change</a>
 <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
 <a class="tag" href="/tag/thinking/page/1/">thinking</a>
 <a class="tag" href="/tag/world/page/1/">world</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
 <span>by <small class="author" itemprop="author">J.K. Rowling</small>
 <a href="/author/J-K-Rowling">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
 <a class="tag" href="/tag/abilities/page/1/">abilities</a>
 <a class="tag" href="/tag/choices/page/1/">choices</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/live/page/1/">live</a>
 <a class="tag" href="/tag/miracle/page/1/">miracle</a>
 <a class="tag" href="/tag/miracles/page/1/">miracles</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
 <span>by <small class="author" itemprop="author">Jane Austen</small>
 <a href="/author/Jane-Austen">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
 <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
 <a class="tag" href="/tag/books/page/1/">books</a>
 <a class="tag" href="/tag/classic/page/1/">classic</a>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
 <span>by <small class="author" itemprop="author">Marilyn Monroe</small>
 <a href="/author/Marilyn-Monroe">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
 <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
 <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
 <a class="tag" href="/tag/success/page/1/">success</a>
 <a class="tag" href="/tag/value/page/1/">value</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
 <span>by <small class="author" itemprop="author">André Gide</small>
 <a href="/author/Andre-Gide">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="life,love" itemprop="keywords"/>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/love/page/1/">love</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
 <span>by <small class="author" itemprop="author">Thomas A. Edison</small>
 <a href="/author/Thomas-A-Edison">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
 <a class="tag" href="/tag/edison/page/1/">edison</a>
 <a class="tag" href="/tag/failure/page/1/">failure</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
 <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
 <a href="/author/Eleanor-Roosevelt">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
 <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
 <span>by <small class="author" itemprop="author">Steve Martin</small>
 <a href="/author/Steve-Martin">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 <a class="tag" href="/tag/obvious/page/1/">obvious</a>
 <a class="tag" href="/tag/simile/page/1/">simile</a>
 </div>
 </div>
 <nav>
 <ul class="pager">
 <li class="next">
 <a href="/page/2/">Next <span aria-hidden="true">→</span></a>
 </li>
 </ul>
 </nav>
 </div>
 <div class="col-md-4 tags-box">
 <h2>Top Ten tags</h2>
 <span class="tag-item">
 <a class="tag" href="/tag/love/" style="font-size: 28px">love</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/inspirational/" style="font-size: 26px">inspirational</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/life/" style="font-size: 26px">life</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/humor/" style="font-size: 24px">humor</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/books/" style="font-size: 22px">books</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/reading/" style="font-size: 14px">reading</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/friendship/" style="font-size: 10px">friendship</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/friends/" style="font-size: 8px">friends</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/truth/" style="font-size: 8px">truth</a>
 </span>
 <span class="tag-item">
 <a class="tag" href="/tag/simile/" style="font-size: 6px">simile</a>
 </span>
 </div>
 </div>
 </div>
 <footer class="footer">
 <div class="container">
 <p class="text-muted">
                 Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
 </p>
 <p class="copyright">
                 Made with <span class="zyte">❤</span> by <a class="zyte" href="https://www.zyte.com">Zyte</a>
 </p>
 </div>
 </footer>
 </body>,
 <div class="container">
 <div class="row header-box">
 <div class="col-md-8">
 <h1>
 <a href="/" style="text-decoration: none">Quotes to Scrape</a>
 </h1>
 </div>
 <div class="col-md-4">
 <p>
 <a href="/login">Login</a>
 </p>
 </div>
 </div>
 <div class="row">
 <div class="col-md-8">
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
 <a class="tag" href="/tag/change/page/1/">change</a>
 <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
 <a class="tag" href="/tag/thinking/page/1/">thinking</a>
 <a class="tag" href="/tag/world/page/1/">world</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
 <span>by <small class="author" itemprop="author">J.K. Rowling</small>
 <a href="/author/J-K-Rowling">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
 <a class="tag" href="/tag/abilities/page/1/">abilities</a>
 <a class="tag" href="/tag/choices/page/1/">choices</a>
 </div>
 </div>
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/live/page/1/">live</a>

In [11]:
quotes = soup.find_all("span", class_="text")

In [12]:
len(quotes)

10

In [13]:
for quote in quotes[:]:
    print(quote.get_text())

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
“Try not to become a man of success. Rather become a man of value.”
“It is better to be hated for what you are than to be loved for what you are not.”
“I have not failed. I've just found 10,000 ways that won't work.”
“A woman is like a tea bag; you never know how strong it is until it's in hot water.”
“A day without sunshine is like, you know, night.”

So far so good, right?

By the way, do you still remember

.....

...

.

RegEx???



```
<span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
```



> <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>

In [14]:
import re

pattern = r'<span[^>]*>(.*?)</span>'

quotes = re.findall(pattern, response.text)

len(quotes)

12

In [15]:
quotes

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
 '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
 '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
 '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
 '“Imperfection is beauty, madness is genius and it&#39;s better to be absolutely ridiculous than absolutely boring.”',
 '“Try not to become a man of success. Rather become a man of value.”',
 '“It is better to be hated for what you are than to be loved for what you are not.”',
 '“I have not failed. I&#39;ve just found 10,000 ways that won&#39;t work.”',
 '“A woman is like a tea bag; you never know how strong it is until it&#39;s in hot water.”',
 '“A day without sunshine is like, you know, night.”',
 '&rarr;',
 '❤']

Notice that it's still not so clean. This means you can do a lot more pre-processing to your output.

## Next Step: Trip over your own shoelaces and faceplant

*Kidding*

Let's try different website.

In [16]:
url = 'https://www.worldometers.info/world-population/population-by-country/'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')
# print(soup)

This time, let's work with tables.

In [17]:
soup.find_all('table')

[<table class="datatable w-full border border-zinc-200" data-locale="en" data-options='{"searchable":true,"sortable":true,"defaultSort":"#","pageSize":false}' data-sort-col="0" data-sort-dir="asc" id=""> <thead> <tr> <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>#</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>Country (or dependency)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Population 2026</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Yearly Change</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Net Change</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Density (P/KmÂ²)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Land Area (KmÂ²)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Migrants (net)</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Fert. Rate</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Median Age</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Urban Pop %</span> </th><th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>World Share</span> </th> </tr> </thead> <tbody> <tr id="india"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 1 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/india-population/"> India </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14766255760000" dir="ltr"> 1,476,625,576 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87" dir="ltr"> 0.87% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="127600510000" dir="ltr"> 12,760,051 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4966469" dir="ltr"> 497 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="29731900000" dir="ltr"> 2,973,190 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-4404560000" dir="ltr"> â440,456 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19290" dir="ltr"> 1.93 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292160" dir="ltr"> 29.2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3761" dir="ltr"> 37.6% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1779" dir="ltr"> 17.8% </td> </tr><tr id="china"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/china-population/"> China </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14129140890000" dir="ltr"> 1,412,914,089 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-22" dir="ltr"> â0.22% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-31820050000" dir="ltr"> â3,182,005 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1504988" dir="ltr"> 150 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="93882110000" dir="ltr"> 9,388,211 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2321070000" dir="ltr"> â232,107 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10310" dir="ltr"> 1.03 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406480" dir="ltr"> 40.6 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6868" dir="ltr"> 68.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1702" dir="ltr"> 17% </td> </tr><tr id="us"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/us-population/"> United States </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="3490354940000" dir="ltr"> 349,035,494 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="51" dir="ltr"> 0.51% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="17596870000" dir="ltr"> 1,759,687 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="381567" dir="ltr"> 38 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="91474200000" dir="ltr"> 9,147,420 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="11778480000" dir="ltr"> 1,177,848 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="16250" dir="ltr"> 1.63 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="387130" dir="ltr"> 38.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8313" dir="ltr"> 83.1% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="420" dir="ltr"> 4.2% </td> </tr><tr id="indonesia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 4 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/indonesia-population/"> Indonesia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2878867820000" dir="ltr"> 287,886,782 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="76" dir="ltr"> 0.76% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21655460000" dir="ltr"> 2,165,546 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1589156" dir="ltr"> 159 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18115700000" dir="ltr"> 1,811,570 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-394720000" dir="ltr"> â39,472 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20800" dir="ltr"> 2.08 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="306590" dir="ltr"> 30.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6027" dir="ltr"> 60.3% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="347" dir="ltr"> 3.5% </td> </tr><tr id="pakistan"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 5 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/pakistan-population/"> Pakistan </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2592997910000" dir="ltr"> 259,299,791 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.6% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="40802370000" dir="ltr"> 4,080,237 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3363686" dir="ltr"> 336 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7708800000" dir="ltr"> 770,880 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-11447380000" dir="ltr"> â1,144,738 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34420" dir="ltr"> 3.44 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="207710" dir="ltr"> 20.8 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3470" dir="ltr"> 34.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="312" dir="ltr"> 3.1% </td> </tr><tr id="nigeria"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 6 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/nigeria-population/"> Nigeria </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2424318320000" dir="ltr"> 242,431,832 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="206" dir="ltr"> 2.06% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="49040500000" dir="ltr"> 4,904,050 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2661834" dir="ltr"> 266 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9107700000" dir="ltr"> 910,770 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-28100000" dir="ltr"> â2,810 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="42050" dir="ltr"> 4.21 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="183480" dir="ltr"> 18.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="5580" dir="ltr"> 55.8% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292" dir="ltr"> 2.9% </td> </tr><tr id="brazil"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/brazil-population/"> Brazil </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2135626660000" dir="ltr"> 213,562,666 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="35" dir="ltr"> 0.35% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7502610000" dir="ltr"> 750,261 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="255515" dir="ltr"> 26 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="83581400000" dir="ltr"> 8,358,140 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2056420000" dir="ltr"> â205,642 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="15910" dir="ltr"> 1.59 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="352500" dir="ltr"> 35.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9174" dir="ltr"> 91.7% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="257" dir="ltr"> 2.6% </td> </tr><tr id="bangladesh"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 8 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/bangladesh-population/"> Bangladesh </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1778180440000" dir="ltr"> 177,818,044 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="121" dir="ltr"> 1.21% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21311450000" dir="ltr"> 2,131,145 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="13660447" dir="ltr"> 1,366 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1301700000" dir="ltr"> 130,170 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-3713980000" dir="ltr"> â371,398 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20900" dir="ltr"> 2.09 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="263020" dir="ltr"> 26.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4321" dir="ltr"> 43.2% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="214" dir="ltr"> 2.1% </td> </tr><tr id="russia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 9 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/russia-population/"> Russia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1433944580000" dir="ltr"> 143,394,458 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-42" dir="ltr"> â0.42% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6029350000" dir="ltr"> â602,935 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87559" dir="ltr"> 9 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="163768700000" dir="ltr"> 16,376,870 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3249240000" dir="ltr"> 324,924 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="14700" dir="ltr"> 1.47 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406950" dir="ltr"> 40.7 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7541" dir="ltr"> 75.4% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="173" dir="ltr"> 1.7% </td> </tr><tr id="ethiopia"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 10 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/ethiopia-population/"> Ethiopia </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1389021850000" dir="ltr"> 138,902,185 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="253" dir="ltr"> 2.53% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34301340000" dir="ltr"> 3,430,134 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1389022" dir="ltr"> 139 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10000000000" dir="ltr"> 1,000,000 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="272980000" dir="ltr"> 27,298 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="37230" dir="ltr"> 3.72 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="193410" dir="ltr"> 19.3 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2290" dir="ltr"> 22.9% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="167" dir="ltr"> 1.7% </td> </tr><tr id="mexico"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 11 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/mexico-population/"> Mexico </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1329976580000" dir="ltr"> 132,997,658 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="80" dir="ltr"> 0.8% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10507580000" dir="ltr"> 1,050,758 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="684162" dir="ltr"> 68 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19439500000" dir="ltr"> 1,943,950 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-1098440000" dir="ltr"> â109,844 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18520" dir="ltr"> 1.85 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="299950" dir="ltr"> 30 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8830" dir="ltr"> 88.3% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.6% </td> </tr><tr id="japan"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 12 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/japan-population/"> Japan </a> </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1224277310000" dir="ltr"> 122,427,731 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-55" dir="ltr"> â0.55% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6757480000" dir="ltr"> â675,748 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3358279" dir="ltr"> 336 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3645550000" dir="ltr"> 364,555 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1286190000" dir="ltr"> 128,619 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="12310" dir="ltr"> 1.23 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="501810" dir="ltr"> 50.2 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9335" dir="ltr"> 93.4% </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="147" dir="ltr"> 1.5% </td> </tr><tr id="egypt"> <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 13 </td><td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro

Let's first get just the title of the table.

*Note: `<th>` tag defines a header cell in an HTML table*

In [18]:
titles = soup.find_all('th')
titles

[<th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>#</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>Country (or dependency)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Population 2026</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Yearly Change</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Net Change</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Density (P/KmÂ²)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Land Area (KmÂ²)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Migrants (net)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Fert. Rate</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Median Age</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Urban Pop %</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>World Share</span> </th>]

Since we do not need the tags, let's clean up the data.

In [19]:
titles_list = [title.text for title in titles]
len(titles_list)

12

In [20]:
titles_list

[' # ',
 ' Country (or dependency) ',
 ' Population 2026 ',
 ' Yearly Change ',
 ' Net Change ',
 ' Density (P/KmÂ²) ',
 ' Land Area (KmÂ²) ',
 ' Migrants (net) ',
 ' Fert. Rate ',
 ' Median Age ',
 ' Urban Pop % ',
 ' World Share ']

If the output still contains newline and other symbols that are not needed, you can further clean the data using, for example, ```.strip()```

Next, create a dataframe

In [21]:
import pandas as pd

df = pd.DataFrame(columns = titles_list)
df

Empty DataFrame
Columns: [ # ,  Country (or dependency) ,  Population 2026 ,  Yearly Change ,  Net Change ,  Density (P/KmÂ²) ,  Land Area (KmÂ²) ,  Migrants (net) ,  Fert. Rate ,  Median Age ,  Urban Pop % ,  World Share ]
Index: []

Let's scrape the remaining data and fill this table!

In [22]:
rows = soup.find_all('tr')
len(rows)

235

The data of our interest are within the scope of **td** tags.

*Note: `<td>` tag defines a standard data cell in an HTML table.*

In [23]:
# -- Long version --
# row_data = []
# for row in rows:
#   row_data.append(row.find_all('td'))

# -- Short version --
row_data = [row.find_all('td') for row in rows]
row_data

[[],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 1 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/india-population/"> India </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14766255760000" dir="ltr"> 1,476,625,576 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87" dir="ltr"> 0.87% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="127600510000" dir="ltr"> 12,760,051 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4966469" dir="ltr"> 497 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="29731900000" dir="ltr"> 2,973,190 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-4404560000" dir="ltr"> â440,456 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19290" dir="ltr"> 1.93 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292160" dir="ltr"> 29.2 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3761" dir="ltr"> 37.6% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1779" dir="ltr"> 17.8% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 2 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/china-population/"> China </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14129140890000" dir="ltr"> 1,412,914,089 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-22" dir="ltr"> â0.22% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-31820050000" dir="ltr"> â3,182,005 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1504988" dir="ltr"> 150 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="93882110000" dir="ltr"> 9,388,211 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2321070000" dir="ltr"> â232,107 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10310" dir="ltr"> 1.03 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406480" dir="ltr"> 40.6 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6868" dir="ltr"> 68.7% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1702" dir="ltr"> 17% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 3 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/us-population/"> United States </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="3490354940000" dir="ltr"> 349,035,494 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="51" dir="ltr"> 0.51% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="17596870000" dir="ltr"> 1,759,687 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="381567" dir="ltr"> 38 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="91474200000" dir="ltr"> 9,147,420 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="11778480000" dir="ltr"> 1,177,848 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="16250" dir="ltr"> 1.63 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="387130" dir="ltr"> 38.7 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8313" dir="ltr"> 83.1% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="420" dir="ltr"> 4.2% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 4 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/indonesia-population/"> Indonesia </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2878867820000" dir="ltr"> 287,886,782 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="76" dir="ltr"> 0.76% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21655460000" dir="ltr"> 2,165,546 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1589156" dir="ltr"> 159 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18115700000" dir="ltr"> 1,811,570 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-394720000" dir="ltr"> â39,472 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20800" dir="ltr"> 2.08 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="306590" dir="ltr"> 30.7 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="6027" dir="ltr"> 60.3% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="347" dir="ltr"> 3.5% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 5 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/pakistan-population/"> Pakistan </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2592997910000" dir="ltr"> 259,299,791 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.6% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="40802370000" dir="ltr"> 4,080,237 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3363686" dir="ltr"> 336 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7708800000" dir="ltr"> 770,880 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-11447380000" dir="ltr"> â1,144,738 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34420" dir="ltr"> 3.44 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="207710" dir="ltr"> 20.8 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3470" dir="ltr"> 34.7% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="312" dir="ltr"> 3.1% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 6 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/nigeria-population/"> Nigeria </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2424318320000" dir="ltr"> 242,431,832 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="206" dir="ltr"> 2.06% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="49040500000" dir="ltr"> 4,904,050 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2661834" dir="ltr"> 266 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9107700000" dir="ltr"> 910,770 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-28100000" dir="ltr"> â2,810 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="42050" dir="ltr"> 4.21 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="183480" dir="ltr"> 18.3 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="5580" dir="ltr"> 55.8% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292" dir="ltr"> 2.9% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 7 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/brazil-population/"> Brazil </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="2135626660000" dir="ltr"> 213,562,666 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="35" dir="ltr"> 0.35% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7502610000" dir="ltr"> 750,261 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="255515" dir="ltr"> 26 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="83581400000" dir="ltr"> 8,358,140 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-2056420000" dir="ltr"> â205,642 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="15910" dir="ltr"> 1.59 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="352500" dir="ltr"> 35.3 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9174" dir="ltr"> 91.7% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="257" dir="ltr"> 2.6% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 8 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/bangladesh-population/"> Bangladesh </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1778180440000" dir="ltr"> 177,818,044 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="121" dir="ltr"> 1.21% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="21311450000" dir="ltr"> 2,131,145 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="13660447" dir="ltr"> 1,366 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1301700000" dir="ltr"> 130,170 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-3713980000" dir="ltr"> â371,398 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="20900" dir="ltr"> 2.09 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="263020" dir="ltr"> 26.3 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4321" dir="ltr"> 43.2% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="214" dir="ltr"> 2.1% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 9 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/russia-population/"> Russia </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1433944580000" dir="ltr"> 143,394,458 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-42" dir="ltr"> â0.42% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6029350000" dir="ltr"> â602,935 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87559" dir="ltr"> 9 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="163768700000" dir="ltr"> 16,376,870 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3249240000" dir="ltr"> 324,924 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="14700" dir="ltr"> 1.47 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="406950" dir="ltr"> 40.7 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="7541" dir="ltr"> 75.4% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="173" dir="ltr"> 1.7% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 10 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/ethiopia-population/"> Ethiopia </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1389021850000" dir="ltr"> 138,902,185 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="253" dir="ltr"> 2.53% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="34301340000" dir="ltr"> 3,430,134 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1389022" dir="ltr"> 139 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10000000000" dir="ltr"> 1,000,000 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="272980000" dir="ltr"> 27,298 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="37230" dir="ltr"> 3.72 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="193410" dir="ltr"> 19.3 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="2290" dir="ltr"> 22.9% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="167" dir="ltr"> 1.7% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 11 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/mexico-population/"> Mexico </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1329976580000" dir="ltr"> 132,997,658 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="80" dir="ltr"> 0.8% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="10507580000" dir="ltr"> 1,050,758 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="684162" dir="ltr"> 68 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19439500000" dir="ltr"> 1,943,950 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-1098440000" dir="ltr"> â109,844 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="18520" dir="ltr"> 1.85 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="299950" dir="ltr"> 30 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="8830" dir="ltr"> 88.3% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="160" dir="ltr"> 1.6% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 12 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/japan-population/"> Japan </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1224277310000" dir="ltr"> 122,427,731 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-55" dir="ltr"> â0.55% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-6757480000" dir="ltr"> â675,748 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3358279" dir="ltr"> 336 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3645550000" dir="ltr"> 364,555 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1286190000" dir="ltr"> 128,619 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="12310" dir="ltr"> 1.23 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="501810" dir="ltr"> 50.2 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9335" dir="ltr"> 93.4% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="147" dir="ltr"> 1.5% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 13 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/egypt-population/"> Egypt </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1201011750000" dir="ltr"> 120,101,175 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="147" dir="ltr"> 1.47% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="17351800000" dir="ltr"> 1,735,180 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1206501" dir="ltr"> 121 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9954500000" dir="ltr"> 995,450 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-522870000" dir="ltr"> â52,287 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="26830" dir="ltr"> 2.68 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="246970" dir="ltr"> 24.7 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4112" dir="ltr"> 41.1% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="145" dir="ltr"> 1.4% </td>],
 [<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 14 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/philippines-population/"> Philippines </a> </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="1177244710000" dir="ltr"> 117,724,471 </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="80" dir="ltr"> 0.8% </td>,
  <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="9375090000" dir="ltr"> 937,509 </td>,

The first row collected has no value, thus an empty list.

In [24]:
row_data[0]

[]

Turns out the first row is actually here

In [25]:
row_data[1]

[<td class="border-e border-zinc-200 px-2 border-b py-1.5 text-start"> 1 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 font-bold text-start"> <a class="transition-colors text-primary hover:text-primary/80" data-astro-reload="true" href="/world-population/india-population/"> India </a> </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end font-bold" data-order="14766255760000" dir="ltr"> 1,476,625,576 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="87" dir="ltr"> 0.87% </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="127600510000" dir="ltr"> 12,760,051 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="4966469" dir="ltr"> 497 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="29731900000" dir="ltr"> 2,973,190 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="-4404560000" dir="ltr"> â440,456 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="19290" dir="ltr"> 1.93 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="292160" dir="ltr"> 29.2 </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="3761" dir="ltr"> 37.6% </td>,
 <td class="border-e border-zinc-200 px-2 border-b py-1.5 text-end" data-order="1779" dir="ltr"> 17.8% </td>]

However, we only want the text portion.

In [26]:
print(row_data[1][0].text)
print(row_data[1][1].text)
print(row_data[1][2].text)
print(row_data[1][3].text)

 1
  India
 1,476,625,576
 0.87%

Therefore, more cleaning is necessary.

Add the remaining rows to the dataframe.

But does this code work?

In [27]:
# for each_row_data in row_data:
#     state=[]
#     for each_row_data_elem in each_row_data:
#         state.append(each_row_data_elem.text)
#     print(state)
#     length = len(df)
#     df.loc[length] = state

Now, try again...

In [28]:
for each_row_data in row_data:
  if not each_row_data:  # Skip empty lists
    continue
  state=[]
  for each_row_data_elem in each_row_data:
    state.append(each_row_data_elem.text)

  length = len(df)
  df.loc[length] = state

In [29]:
df

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/KmÂ²),Land Area (KmÂ²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","â440,456",1.93,29.2,37.6%,17.8%
1,2,China,"1,412,914,089",â0.22%,"â3,182,005",150,"9,388,211","â232,107",1.03,40.6,68.7%,17%
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.2%
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","â39,472",2.08,30.7,60.3%,3.5%
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","â1,144,738",3.44,20.8,34.7%,3.1%
...,...,...,...,...,...,...,...,...,...,...,...,...
229,230,Montserrat,"4,328",â0.71%,â31,43,100,â10,1.45,41.8,11.7%,0.000052%
230,231,Falkland Islands,"3,465",â0.12%,â4,0,"12,170",â16,1.69,43.4,68.4%,0.000042%
231,232,Tokelau,"2,691",3.18%,83,269,10,43,2.54,27.6,â,0.000032%
232,233,Niue,"1,822",0.05%,1,7,260,2,2.44,35.1,45.2%,0.000022%
233,234,Holy See,506,1%,5,"1,265",0,13,1,56.2,â,0.0000061%



---

## Final Step: Wrestle Wikipedia (and hope for the best)

Let's explore Bangkok!

In [33]:
url = 'https://en.wikipedia.org/wiki/Bangkok'
headers = {
    "User-Agent": "MeTryingToGetPassTheRule/1.0"
}
page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text)
print(soup)

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Bangkok - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"14243b45-7c4a-4bab-839a-deabcc6c327d","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Bangkok","wgTitle":"Bangkok","wgCurRevisionId":1371562320,"wgRevisionId":1371562320,"wgArticleId":56615,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use Oxford spelling from January 2021","All Wikipedia articles written in British English with Oxford spelling","Use dmy dates from October 2020","Pages using gadget WikiMiniAtlas","Articles containing Thai-language text","Pages using multiple image with auto scaled images","Coordinates on Wikidata","Pages using infobox settlement with deprecated parameters","Pages using the Phonos extension","Pages including recorded pronunciations","Pages with Thai IPA","CS1 uses Thai-language script (th)","CS1 Thai-language sources (th)","Articles with hAudio microformats","CS1 maint: url-status","Webarchive template wayback links","CS1 French-language sources (fr)","All articles with incomplete citations","Articles with incomplete citations from July 2024","Articles with Thai-language sources (th)","All articles with unsourced statements","Articles with unsourced statements from August 2024","Articles needing additional references from April 2021","All articles needing additional references","Articles containing potentially dated statements from 2024","All articles containing potentially dated statements","Articles containing potentially dated statements from August 2012","Articles needing additional references from January 2026","All articles with dead external links","Articles with dead external links from March 2014","CS1: unfit URL","CS1 maint: deprecated archival service","CS1 Italian-language sources (it)","Articles with dead external links from August 2023","Pages using Sister project links with hidden wikidata","Pages using Sister project links with default search","Official website different in Wikidata and Wikipedia","Pages using the Kartographer extension","Bangkok","18th-century establishments in Asia","Capital cities in Asia","Cities and towns in Thailand","Gulf of Thailand","Populated places established in the 18th century","Populated places on the Chao Phraya River","Provinces of Thailand","Megacities","Guinness World Records holders"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Bangkok","wgRelevantArticleId":56615,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":["sysop"],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":200000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgCoordinates":{"lat":13.7525,"lon":100.49416666666667},"wgPageAssessments":{"Cities":{"class":"B","importance":""},"Cities/Core":{"class":"B","importance":""},"Cities/National capitals":{"class":"B","importance":""},"Project-independent assessment":{"class":"B","importance":""},"Southeast Asia":{"class":"B","importance":"Top"},"Thailand":{"class":"B","importance":"Top"}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q1861","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.phonos.styles":"ready","ext.phonos.icons":"ready","mediawiki.page.gallery.styles":"ready","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","ext.tmh.player.styles":"ready","ext.kartographer.style":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.makeCollapsible.styles":"ready","mediawiki.skins.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready","ext.wikimediaBadges.ulsV2":"ready"};RLPAGEMODULES=["ext.kartographer.staticframe","ext.phonos.init","ext.cite.ux-enhancements","mediawiki.page.media","ext.tmh.player","ext.scribunto.logs","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.gadget.WikiMiniAtlas","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.kartographer.style%7Cext.phonos.icons%2Cstyles%7Cext.tmh.player.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediaBadges.ulsV2%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cmediawiki.page.gallery.styles%7Cmediawiki.skinning.content.parsoid%7Cmediawiki.skins.legacy%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.16" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/4Y1A1159_Bangkok_%2833536795515%29.jpg/1280px-4Y1A1159_Bangkok_%2833536795515%29.jpg?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="800" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="Bangkok - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=Bangkok&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/Bangkok" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Bangkok rootpage-Bangkok skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Bangkok" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>

Uh oh.. does it work?